title: "2022 GeOnG - QGIS Workshop"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
color_scheme: calais

# Build settings
markdown: kramdown

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/GEONG_logo_2022_EN.png"

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple

# Regression tests
# By default, the pages in /docs/tests are excluded when the ste is built.
# To include them, comment-out the relevant line above.
# Uncommenting the following line doesn't work - see https://github.com/jekyll/jekyll/issues/4791
# include: ["docs/tests/"]

plugins:
  - jekyll-seo-tag
